#!/bin/sh -eu

LUA_PATH="templates/ssid_changed_callback.lua"
HAMMERSPEEN_CONFIG_PATH_KEY="HAMMERSPEEN_CONFIG_PATH="
HAMMERSPEEN_CONFIG_PATH=$(grep --color=always -E "^$HAMMERSPEEN_CONFIG_PATH_KEY" .env | sed "s/$HAMMERSPEEN_CONFIG_PATH_KEY//")
TARGET_SSID_KEY="TARGET_SSID="
TARGET_SSID=$(grep --color=always -E "^$TARGET_SSID_KEY" .env | sed "s/$TARGET_SSID_KEY//")
SLACK_BOT_TOKEN_KEY="SLACK_BOT_TOKEN="
SLACK_BOT_TOKEN=$(grep --color=always -E "^$SLACK_BOT_TOKEN_KEY" .env | sed "s/$SLACK_BOT_TOKEN_KEY//")
SLACK_BOT_USER_ID_KEY="SLACK_BOT_USER_ID="
SLACK_BOT_USER_ID=$(grep --color=always -E "^$SLACK_BOT_USER_ID_KEY" .env | sed "s/$SLACK_BOT_USER_ID_KEY//")
SLACK_POST_CHANNEL_KEY="SLACK_POST_CHANNEL="
SLACK_POST_CHANNEL=$(grep --color=always -E "^$SLACK_POST_CHANNEL_KEY" .env | sed "s/$SLACK_POST_CHANNEL_KEY//")
CLOCK_IN_TEXT_KEY="CLOCK_IN_TEXT="
CLOCK_IN_TEXT=$(grep --color=always -E "^$CLOCK_IN_TEXT_KEY" .env | sed "s/$CLOCK_IN_TEXT_KEY//")
CLOCK_OUT_TEXT_KEY="CLOCK_OUT_TEXT="
CLOCK_OUT_TEXT=$(grep --color=always -E "^$CLOCK_OUT_TEXT_KEY" .env | sed "s/$CLOCK_OUT_TEXT_KEY//")
POP_DRAFT_TEXT_KEY="POP_DRAFT_TEXT="
POP_DRAFT_TEXT=$(grep --color=always -E "^$POP_DRAFT_TEXT_KEY" .env | sed "s/$POP_DRAFT_TEXT_KEY//")

rm -i $HAMMERSPEEN_CONFIG_PATH/init.lua
sed "s/TARGET_SSID/$TARGET_SSID/g \
; s/SLACK_BOT_TOKEN/$SLACK_BOT_TOKEN/g \
; s/SLACK_BOT_USER_ID/$SLACK_BOT_USER_ID/g \
; s/SLACK_POST_CHANNEL/$SLACK_POST_CHANNEL/g \
; s/CLOCK_IN_TEXT/$CLOCK_IN_TEXT/g \
; s/CLOCK_OUT_TEXT/$CLOCK_OUT_TEXT/g \
; s/POP_DRAFT_TEXT/$POP_DRAFT_TEXT/g" \
< $LUA_PATH \
> $HAMMERSPEEN_CONFIG_PATH/init.lua
